# For production, use git-gateway:
# backend:
#   name: git-gateway
#   branch: main

# For local development, use test-repo:
backend:
  name: test-repo

# Uncomment below to enable editorial workflow
# publish_mode: editorial_workflow

media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Description", name: "description", widget: "string", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
  
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
